pool:
  vmImage: ubuntu-latest
stages:
- stage: cd
  displayName: Continuous deployment
  jobs:
  - job: docker_build_push
    displayName: Build Docker Container image
    steps:
    - task: Docker@2
      displayName: Build and push Docker container image to Azure Container Registry
      inputs:
        containerRegistry: 'doctors_azure_acr'
        repository: 'Doctorswebapp'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
    - task: Docker@2
      displayName: Push container image to Azure Container registry
      inputs:
        containerRegistry: 'doctors_azure_acr'
        repository: 'Doctorswebapp'
        command: 'push'
        tags: |
          $(Build.BuildId)
          latest
